### ISSUE TITLE
pod_vector bug in shrink_at

### ISSUE THREAD

**Issue by Micke632** [iboB/itlib#8]
shrink_at () returns wrong iterator

 T* shrink_at(const T* cp, size_type num)
    {
        const auto s = size();
        if (s == num)
        {
            clear();
            return m_end;
        }

        auto position = const_cast<T*>(cp);

        std::memmove(position, position + num, size_t(m_end - position - num) * sizeof(T));

        m_end -= num;

        return ++position
    }

Should be:

 T* shrink_at(const T* cp, size_type num)
    {
        const auto s = size();
        if (s == num)
        {
            clear();
            return m_end;
        }

        auto position = const_cast<T*>(cp);

        std::memmove(position, position + num, size_t(m_end - position - num) * sizeof(T));

        m_end -= num;

        return position;
    }

**Comment by iboB** [comment]
Oops! you're right, Thanks for noticing. Thanks to copypasta, this also affects `small_vector`.

Will fix in a couple of mintues

**Comment by iboB** [comment]
Fixed in 40b31b284d20a4ffc65610aa7ce3f5c522d5689d
