### ISSUE TITLE
bug in small_vector  resize

### ISSUE THREAD

**Issue by Micke632** [iboB/itlib#9]
Corner case in resize if going from dynamic memory to static , causing corrupt memory.

Reproduce: 
itlib::small_vector<int, 4,3> v(5);
v.resize(2);

but just checking new_buf  in resize() , I think is enough:

   if (m_begin != static_begin_ptr())
    {
           // we've moved from dyn to dyn memory, so deallocate the old one
              if (new_buf != static_begin_ptr())
		   atraits::deallocate(get_alloc(), m_begin, m_capacity);

     }

**Comment by iboB** [comment]
Thanks. Fixed in https://github.com/iboB/itlib/commit/b7642f2e0d4262d1b8b9a31253b994c2ba3fbfba
(forgot to tag issue in commit message)
